# Standalone Makefile (no IDE dependency)
# Extracted from obj/ autogenerated makefiles

# Project
PROJECT := RISKYMSXCART
FIRMWARE_DIR := firmware
OUTDIR  := $(FIRMWARE_DIR)/build

# Extract version from version.h
VERSION_FILE := $(FIRMWARE_DIR)/User/version.h
FIRMWARE_VERSION := $(shell grep 'FIRMWARE_VERSION_STRING' $(VERSION_FILE) | sed 's/.*"\(.*\)".*/\1/' | tr -d ' ')

# Toolchain (override TOOLCHAIN_PREFIX if needed)
TOOLCHAIN_PATH := /usr/share/MRS2/MRS-linux-x64/resources/app/resources/linux/components/WCH/Toolchain/RISC-V\ Embedded\ GCC12/bin
TOOLCHAIN_PREFIX ?= $(TOOLCHAIN_PATH)/riscv-wch-elf
CC       := $(TOOLCHAIN_PREFIX)-gcc
OBJCOPY  := $(TOOLCHAIN_PREFIX)-objcopy
OBJDUMP  := $(TOOLCHAIN_PREFIX)-objdump
SIZE     := $(TOOLCHAIN_PREFIX)-size
RM       := rm -rf

# WCH Programming tools
WCH_OPENOCD := /usr/share/MRS2/MRS-linux-x64/resources/app/resources/linux/components/WCH/OpenOCD/OpenOCD/bin/openocd
WCH_ISP := wchisptool

# CPU/ABI flags (from IDE)
ARCH := rv32imacxw
ABI  := ilp32
CPUFLAGS := -march=$(ARCH) -mabi=$(ABI) -msmall-data-limit=8 -msave-restore

# Include paths (from IDE)
INCLUDES := \
  -I$(FIRMWARE_DIR)/Debug \
  -I$(FIRMWARE_DIR)/Core \
  -I$(FIRMWARE_DIR)/User \
  -I$(FIRMWARE_DIR)/Peripheral/inc \
  -I$(FIRMWARE_DIR)/User/USB_Host \
  -I$(FIRMWARE_DIR)/User/FATFS

# Compilation flags (from IDE)
COMMON_WARN   := -Wunused -Wuninitialized
COMMON_OPTS   := -fmax-errors=20 -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -std=gnu99
COMPILE_FLAGS := $(CPUFLAGS) $(COMMON_OPTS) $(COMMON_WARN)
CFLAGS        := $(COMPILE_FLAGS) $(INCLUDES) -Wa,-adhlns="$@.lst" -v -MMD -MP
ASFLAGS       := $(CPUFLAGS) -x assembler-with-cpp -I$(FIRMWARE_DIR)/Startup -I$(FIRMWARE_DIR)/User -v -MMD -MP

# Linker script and flags (from IDE)
LDSCRIPT := $(FIRMWARE_DIR)/Ld/Link.ld
LDFLAGS  := -T $(LDSCRIPT) -nostartfiles -Xlinker --gc-sections -Wl,-Map,"$(OUTDIR)/$(PROJECT).map" --specs=nano.specs --specs=nosys.specs

# Sources (explicit lists based on IDE makefiles to avoid unintended extras)
CORE_SRCS   := $(FIRMWARE_DIR)/Core/core_riscv.c
DEBUG_SRCS  := $(FIRMWARE_DIR)/Debug/debug.c
PERIPH_SRCS := \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_dac.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_dbgmcu.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_dma.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_exti.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_flash.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_gpio.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_iwdg.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_misc.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_pwr.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_rcc.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_rng.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_sdio.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_tim.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_usart.c \
  $(FIRMWARE_DIR)/Peripheral/src/ch32v30x_wwdg.c
USER_SRCS   := \
  $(FIRMWARE_DIR)/User/MSXTerminal.c \
  $(FIRMWARE_DIR)/User/cart.c \
  $(FIRMWARE_DIR)/User/ch32v30x_it.c \
  $(FIRMWARE_DIR)/User/emu2212.c \
  $(FIRMWARE_DIR)/User/gpio.c \
  $(FIRMWARE_DIR)/User/main.c \
  $(FIRMWARE_DIR)/User/programflash.c \
  $(FIRMWARE_DIR)/User/scc.c \
  $(FIRMWARE_DIR)/User/set_memory_split.c \
  $(FIRMWARE_DIR)/User/system_ch32v30x.c \
  $(FIRMWARE_DIR)/User/utils.c
FATFS_SRCS  := \
  $(FIRMWARE_DIR)/User/FATFS/diskio.c \
  $(FIRMWARE_DIR)/User/FATFS/ff.c \
  $(FIRMWARE_DIR)/User/FATFS/ffsystem.c \
  $(FIRMWARE_DIR)/User/FATFS/ffunicode.c \
  $(FIRMWARE_DIR)/User/FATFS/usb_disk.c
USB_SRCS    := \
  $(FIRMWARE_DIR)/User/USB_Host/ch32v30x_usbfs_host.c

C_SOURCES := $(CORE_SRCS) $(DEBUG_SRCS) $(PERIPH_SRCS) $(USER_SRCS) $(FATFS_SRCS) $(USB_SRCS)

ASM_SOURCES := $(wildcard $(FIRMWARE_DIR)/Startup/*.S)

# Objects and deps (preserve directory structure under OUTDIR)
COBJS := $(patsubst $(FIRMWARE_DIR)/%.c,$(OUTDIR)/$(FIRMWARE_DIR)/%.o,$(C_SOURCES))
AOBJS := $(patsubst $(FIRMWARE_DIR)/%.S,$(OUTDIR)/$(FIRMWARE_DIR)/%.o,$(ASM_SOURCES))
OBJS  := $(COBJS) $(AOBJS)
DEPS  := $(OBJS:.o=.d)

# Default goal
.PHONY: all
all: $(OUTDIR)/$(PROJECT).elf post-build

# Help target
.PHONY: help
help:
	@echo "Available targets:"
	@echo "  all          - Build the entire project (default)"
	@echo "  clean        - Remove all build artifacts"
	@echo "  version      - Show firmware version"
	@echo "  size         - Show binary size information"
	@echo "  list         - Generate disassembly listing"
	@echo "  program      - Program binary to WCH chip via ISP (USB bootloader)"
	@echo "  flash        - Program binary to WCH chip via OpenOCD (SWD/JTAG)"
	@echo "  erase        - Erase chip via ISP (USB bootloader)"
	@echo "  erase-flash  - Erase chip via OpenOCD (SWD/JTAG)"
	@echo "  upload       - Build and program via ISP in one step"
	@echo "  full-program - Build, erase and program via ISP"
	@echo "  full-flash   - Build, erase and program via OpenOCD"
	@echo "  test-program - Test programming setup without programming"
	@echo "  program-help - Show detailed programming instructions"
	@echo "  help         - Show this help message"
	@echo ""
	@echo "Build output:"
	@echo "  Build files: $(OUTDIR)/"
	@echo "  Final binary: $(PROJECT)_$(FIRMWARE_VERSION).bin"

# Link
$(OUTDIR)/$(PROJECT).elf: $(OBJS) | $(OUTDIR)
	$(CC) $(COMPILE_FLAGS) $(LDFLAGS) -o $@ $(OBJS)

# Post-build artifacts (match IDE)
.PHONY: post-build
post-build: $(OUTDIR)/$(PROJECT).hex $(OUTDIR)/$(PROJECT).bin $(OUTDIR)/$(PROJECT).lst $(OUTDIR)/$(PROJECT).siz copy-binary

$(OUTDIR)/$(PROJECT).bin: $(OUTDIR)/$(PROJECT).elf | $(OUTDIR)
	$(OBJCOPY) -O binary $< $@

$(OUTDIR)/$(PROJECT).hex: $(OUTDIR)/$(PROJECT).elf | $(OUTDIR)
	$(OBJCOPY) -O ihex $< $@

$(OUTDIR)/$(PROJECT).lst: $(OUTDIR)/$(PROJECT).elf | $(OUTDIR)
	$(OBJDUMP) --all-headers --demangle --disassemble -M xw $< > $@

$(OUTDIR)/$(PROJECT).siz: $(OUTDIR)/$(PROJECT).elf | $(OUTDIR)
	$(SIZE) --format=berkeley $< > $@

# Copy binary to main folder with version name
.PHONY: copy-binary
copy-binary: $(OUTDIR)/$(PROJECT).bin
	@echo "Copying binary with version $(FIRMWARE_VERSION)"
	cp $(OUTDIR)/$(PROJECT).bin $(PROJECT)_$(FIRMWARE_VERSION).bin
	@echo "Binary copied to: $(PROJECT)_$(FIRMWARE_VERSION).bin"

# Compile C -> object (with per-file .lst and .d)
$(OUTDIR)/$(FIRMWARE_DIR)/%.o: $(FIRMWARE_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c -o $@ $< -MF $(@:.o=.d) -MT $@

# Assemble S -> object (with .d)
$(OUTDIR)/$(FIRMWARE_DIR)/%.o: $(FIRMWARE_DIR)/%.S
	@mkdir -p $(dir $@)
	$(CC) $(ASFLAGS) -c -o $@ $< -MF $(@:.o=.d) -MT $@

$(OUTDIR):
	@mkdir -p $(OUTDIR)

# Clean
.PHONY: clean
clean:
	$(RM) $(OUTDIR)

# Include dependencies
-include $(DEPS)

# Convenience targets
.PHONY: size list version
size: $(OUTDIR)/$(PROJECT).siz
list: $(OUTDIR)/$(PROJECT).lst
version:
	@echo "Firmware version: $(FIRMWARE_VERSION)"

# Programming targets
.PHONY: program flash erase erase-flash

# Program using WCH ISP tool (USB bootloader mode)
program: $(OUTDIR)/$(PROJECT).bin
	@echo "Programming $(PROJECT)_$(FIRMWARE_VERSION).bin to WCH chip via ISP..."
	@if [ -f "$(WCH_ISP)" ]; then \
		$(WCH_ISP) -f $(OUTDIR)/$(PROJECT).bin; \
	elif command -v wchisptool >/dev/null 2>&1; then \
		wchisptool -f $(OUTDIR)/$(PROJECT).bin; \
	else \
		echo "Error: WCH ISP tool not found. Please install wchisptool or check path."; \
		echo "Make sure the chip is in bootloader mode (hold BOOT button while resetting)."; \
		exit 1; \
	fi

# Program using OpenOCD (SWD/JTAG interface)
flash: $(OUTDIR)/$(PROJECT).elf
	@echo "Programming $(PROJECT)_$(FIRMWARE_VERSION).bin to WCH chip via OpenOCD..."
	@if [ -f "$(WCH_OPENOCD)" ]; then \
		$(WCH_OPENOCD) -f /usr/share/MRS2/MRS-linux-x64/resources/app/resources/linux/components/WCH/OpenOCD/OpenOCD/bin/wch-riscv.cfg \
		-c "program $(OUTDIR)/$(PROJECT).elf verify reset exit"; \
	elif command -v openocd >/dev/null 2>&1; then \
		openocd -f /usr/share/MRS2/MRS-linux-x64/resources/app/resources/linux/components/WCH/OpenOCD/OpenOCD/bin/wch-riscv.cfg \
		-c "program $(OUTDIR)/$(PROJECT).elf verify reset exit"; \
	else \
		echo "Error: OpenOCD not found. Please install OpenOCD or check path."; \
		echo "Make sure WCH-Link or compatible debugger is connected."; \
		exit 1; \
	fi

# Erase chip using WCH ISP tool (USB bootloader mode)
erase:
	@echo "Erasing WCH chip via ISP..."
	@if [ -f "$(WCH_ISP)" ]; then \
		$(WCH_ISP) -e; \
	elif command -v wchisptool >/dev/null 2>&1; then \
		wchisptool -e; \
	else \
		echo "Error: WCH ISP tool not found. Please install wchisptool or check path."; \
		echo "Make sure the chip is in bootloader mode (hold BOOT button while resetting)."; \
		exit 1; \
	fi

# Erase chip using OpenOCD (SWD/JTAG interface)
erase-flash:
	@echo "Erasing WCH chip via OpenOCD..."
	@if [ -f "$(WCH_OPENOCD)" ]; then \
		$(WCH_OPENOCD) -f /usr/share/MRS2/MRS-linux-x64/resources/app/resources/linux/components/WCH/OpenOCD/OpenOCD/bin/wch-riscv.cfg \
		-c "init; reset halt; flash erase_sector 0 0 last; exit"; \
	elif command -v openocd >/dev/null 2>&1; then \
		openocd -f /usr/share/MRS2/MRS-linux-x64/resources/app/resources/linux/components/WCH/OpenOCD/OpenOCD/bin/wch-riscv.cfg \
		-c "init; reset halt; flash erase_sector 0 0 last; exit"; \
	else \
		echo "Error: OpenOCD not found. Please install OpenOCD or check path."; \
		echo "Make sure WCH-Link or compatible debugger is connected."; \
		exit 1; \
	fi

# Show programming help
.PHONY: program-help
program-help:
	@echo "Programming options:"
	@echo ""
	@echo "1. USB ISP Programming (make program):"
	@echo "   - Put chip in bootloader mode (hold BOOT button while resetting)"
	@echo "   - Connect via USB"
	@echo "   - Run: make program"
	@echo ""
	@echo "2. SWD/JTAG Programming (make flash):"
	@echo "   - Connect WCH-Link or compatible debugger"
	@echo "   - No special mode required"
	@echo "   - Run: make flash"
	@echo ""
	@echo "3. Chip Erase Options:"
	@echo "   - USB ISP Erase: make erase (requires bootloader mode)"
	@echo "   - SWD/JTAG Erase: make erase-flash (requires debugger)"
	@echo ""
	@echo "4. Manual programming:"
	@echo "   - Use wchisptool: wchisptool -f $(PROJECT)_$(FIRMWARE_VERSION).bin"
	@echo "   - Use wchisptool erase: wchisptool -e"
	@echo "   - Use OpenOCD with your config files"
	@echo ""
	@echo "Note: For ISP programming, you may need to install wchisptool separately"
	@echo "      You can download it from WCH official website"

# Build and program in one step
.PHONY: upload
upload: all program
	@echo "Build and programming completed!"

# Erase and program in one step
.PHONY: full-program
full-program: all erase program
	@echo "Full erase and programming completed!"

# Erase and flash in one step (OpenOCD)
.PHONY: full-flash
full-flash: all erase-flash flash
	@echo "Full erase and flash programming completed!"

# Test programming setup without actually programming
.PHONY: test-program
test-program:
	@echo "Testing programming setup..."
	@echo "Checking for programming tools:"
	@if [ -f "$(WCH_OPENOCD)" ]; then \
		echo "✓ WCH OpenOCD found: $(WCH_OPENOCD)"; \
		echo "✓ Config file: /usr/share/MRS2/MRS-linux-x64/resources/app/resources/linux/components/WCH/OpenOCD/OpenOCD/bin/wch-riscv.cfg"; \
	else \
		echo "✗ WCH OpenOCD not found"; \
	fi
	@if command -v wchisptool >/dev/null 2>&1; then \
		echo "✓ wchisptool found in PATH"; \
	else \
		echo "✗ wchisptool not found in PATH"; \
	fi
	@if [ -f "$(OUTDIR)/$(PROJECT).bin" ]; then \
		echo "✓ Binary file ready: $(OUTDIR)/$(PROJECT).bin"; \
	else \
		echo "✗ Binary file not found. Run 'make' first."; \
	fi
	@echo ""
	@echo "Available operations:"
	@echo "  ✓ Programming via ISP (make program)"
	@echo "  ✓ Programming via OpenOCD (make flash)"
	@echo "  ✓ Chip erase via ISP (make erase)"
	@echo "  ✓ Chip erase via OpenOCD (make erase-flash)"
	@echo "  ✓ Full erase + program (make full-program / make full-flash)"
